# Definition of a supported version.
version: '1.0'

# Definition of all sources.
sources:

  # Name of a source. This name will be used as key parametor in http request.
  test_key:

    # Type of source [static, http].
    type: static

    # Cron rule for update data of this source, by default is '0 0 * * * *'.
    rule: '* * * * * *'

    # Value for static source.
    value: test_value


  # Definition of a http source
  ga_count_202103:
    type: http
    rule: '0 */2 * * * *'
    http:
      endpoint: http://analytics-dcb.sigma.sbrf.ru:8123
      method: POST
      header:
      auth:
        user: AdminUser
        password: 'n7C%het*jHFX3^kT!'
      body: >
        SELECT 
          sessionDate, 
          count() 
        FROM GoogleAnalytics.Raw_Data
        PREWHERE toYYYYMM(sessionDate) = 202103
        GROUP BY sessionDate
        ORDER BY sessionDate 