# Definition of a supported version.
version: '1.0'

# Definition of all sources.
sources:

  # Static value
  static_key:
    rule: '* * * * * *'
    static: 
      value: test_value


  # Definition of a http source
  ga_count_202103:
    rule: '0 */2 * * * *'
    http:
      endpoint: http://0.0.0.0:8123
      method: POST
      header:
      auth:
        user: admin
        password: 'adminadmin'
      body: >
        SELECT 
          sessionDate, 
          count() 
        FROM GoogleAnalytics.Raw_Data
        PREWHERE toYYYYMM(sessionDate) = 202103
        GROUP BY sessionDate
        ORDER BY sessionDate 
  
  # Definition of a source on base static file
  file_go.sum:
    rule: '0 */2 * * * *'
    file:
      path: go.sum