name: pr_check

on:
  pull_request:
    branches: 
      - master

jobs:
  
  # It starts all tests on Linux, macOS and Windows for GO version 1.18.
  test:
    strategy:
      matrix:
        go-version: 
          - 1.18.x
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest      
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set environments
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Start tests
        id: all-tests
        run: go test ./... -cover
  
  # If all tests has been successful this PR will approve automatic.
  approve:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    
      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.inputs.pullRequestNumber }}

